image: amirpourmand/al-folio:sha256:d3abe5d18a804eba2df35872ddc20affc701cb49001ad03341a43888712ba928


pages:
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main