image: amirpourmand/al-folio:v0.13.3

stages:
  - build
  - compress
  - deploy

build:
  stage: build
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public

compress:
  stage: compress
  image: alpine:latest
  script:
    - apk add --no-cache gzip brotli
    - |
      find public -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' \) -exec gzip -k -9 {} +
    - |
      find public -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' \) -exec brotli -q 11 {} +
    - |
      echo '/*' > public/.headers &&
      echo '  Content-Encoding: gzip' >> public/.headers &&
      echo '  Cache-Control: max-age=31536000' >> public/.headers &&
      echo '  Content-Type: text/html; charset=utf-8' >> public/.headers &&
      echo '' >> public/.headers &&
      echo '/styles/*.css' >> public/.headers &&
      echo '  Content-Encoding: gzip' >> public/.headers &&
      echo '  Cache-Control: max-age=31536000' >> public/.headers &&
      echo '  Content-Type: text/css; charset=utf-8' >> public/.headers &&
      echo '' >> public/.headers &&
      echo '/scripts/*.js' >> public/.headers &&
      echo '  Content-Encoding: gzip' >> public/.headers &&
      echo '  Cache-Control: max-age=31536000' >> public/.headers &&
      echo '  Content-Type: application/javascript; charset=utf-8' >> public/.headers &&
      echo '' >> public/.headers &&
      echo '/*.html.br' >> public/.headers &&
      echo '  Content-Encoding: br' >> public/.headers &&
      echo '  Content-Type: text/html; charset=utf-8' >> public/.headers &&
      echo '' >> public/.headers &&
      echo '/*.js.br' >> public/.headers &&
      echo '  Content-Encoding: br' >> public/.headers &&
      echo '  Content-Type: application/javascript; charset=utf-8' >> public/.headers
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "Deploying public directory..."
  artifacts:
    paths:
      - public
  only:
    - main