image: ruby:latest

before_script:
  - apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
  - gem install bundler
  - bundle install
  - apt-get install -y python3-pip
  - pip3 install jupyter jupyterlab

pages:
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main